version: "3.9"

# https://github.com/docker/awesome-compose/blob/master/aspnet-mssql/compose.yaml

services:
  sqlserver:
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: 1q2w3e4r!@#
    image: mcr.microsoft.com/mssql/server
    restart: always
    networks:
      - docker_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 1q2w3e4r!@# -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

networks:
  docker_network:
    attachable: true